extends SceneTree


func _initialize() -> void:
	call_deferred("_run")


func _run() -> void:
	var packed: PackedScene = load("res://main.tscn")
	var game: Node = packed.instantiate()
	root.add_child(game)
	await process_frame

	var toggle := InputEventKey.new()
	toggle.pressed = true
	toggle.keycode = KEY_QUOTELEFT
	toggle.physical_keycode = KEY_QUOTELEFT
	toggle.unicode = 96
	game._input(toggle)
	assert(bool(game.gm_console_open))

	game._execute_gm_command("next")
	assert(game.phase == "hunt")
	assert(game.seconds_left == game.HUNT_SECONDS)
	assert(game._treasure_is_in_world("treasure-2"))
	game.attack_until = game.elapsed + game.MONSTER_ATTACK_COOLDOWN
	game._execute_gm_command("cooldown reset B")
	assert(game.attack_until > game.elapsed)
	game._execute_gm_command("cooldown reset all")
	assert(is_equal_approx(game.attack_until, game.elapsed))

	var player_a_actor: Dictionary = game._get_actor(game._role_for_player("A"))
	var player_b_actor: Dictionary = game._get_actor(game._role_for_player("B"))
	var player_a_room: Vector2i = player_a_actor["room"]
	var player_a_pos: Vector2 = player_a_actor["pos"]
	game._execute_gm_command("trans a")
	assert(player_b_actor["room"] == player_a_room)
	assert(player_b_actor["pos"] == player_a_pos)
	assert(bool(game.thief["gm_force_visible"]))
	assert(not bool(game.thief["hidden_from_monster"]))
	assert("玩家B" in str(game.gm_output))
	game.thief["moving"] = true
	game._update_thief_stealth()
	assert(not bool(game.thief["gm_force_visible"]))
	assert(not bool(game.thief["hidden_from_monster"]))
	game.thief["moving"] = false
	game._update_thief_stealth()
	assert(bool(game.thief["hidden_from_monster"]))
	player_b_actor["room"] = Vector2i(2, 3)
	player_b_actor["pos"] = Vector2(1.25, 3.75)
	game._execute_gm_command("trans B")
	assert(player_a_actor["room"] == Vector2i(2, 3))
	assert(player_a_actor["pos"] == Vector2(1.25, 3.75))
	assert("玩家A" in str(game.gm_output))
	game._execute_gm_command("trans C")
	assert("只能填写 A 或 B" in str(game.gm_output))

	game._execute_gm_command("gold B 25")
	assert(int(game.player_coins["B"]) == 25)
	game._execute_gm_command("next")
	assert(game.phase == "shop")
	assert(game.current_round == 1)
	assert(int(game.player_coins["A"]) == 20)

	game._execute_gm_command("give A adrenaline")
	assert((game.player_stashes["A"] as Array).size() == 1)
	assert((game.player_loadouts["A"] as Array).size() == 1)
	game._execute_gm_command("add robot")
	assert((game.player_stashes["A"] as Array).size() == 2)
	assert((game.player_loadouts["A"] as Array).size() == 2)
	assert(str(game._shop_equipped_items("A").back()["tool_type"]) == "robot")
	var player_b_stash_before_invalid := (game.player_stashes["B"] as Array).size()
	game._execute_gm_command("add B 机器人")
	assert((game.player_stashes["B"] as Array).size() == player_b_stash_before_invalid)
	game._execute_gm_command("add B robot")
	assert((game.player_stashes["B"] as Array).size() == 1)
	assert((game.player_loadouts["B"] as Array).size() == 1)
	assert(str(game._shop_equipped_items("B")[0]["tool_type"]) == "robot")
	game._execute_gm_command("next")
	assert(game.phase == "hide")
	assert(game.current_round == 2)
	assert(game._player_for_role("thief") == "A")
	assert((game.tool_inventories["thief"] as Array).size() == 2)
	assert(str(game.tool_inventories["thief"][0]["tool_type"]) == "adrenaline")
	assert(str(game.tool_inventories["thief"][1]["tool_type"]) == "robot")
	assert((game.tool_inventories["monster"] as Array).size() == 1)
	assert(str(game.tool_inventories["monster"][0]["tool_type"]) == "robot")
	var second_round_a: Dictionary = game._get_actor(game._role_for_player("A"))
	var second_round_b: Dictionary = game._get_actor(game._role_for_player("B"))
	var second_round_a_room: Vector2i = second_round_a["room"]
	var second_round_a_pos: Vector2 = second_round_a["pos"]
	game._execute_gm_command("trans A")
	assert(second_round_b["room"] == second_round_a_room)
	assert(second_round_b["pos"] == second_round_a_pos)
	assert(bool(game.thief["gm_force_visible"]))
	assert(not bool(game.thief["hidden_from_monster"]))
	assert(game._role_for_player("A") == "thief")
	assert(game._role_for_player("B") == "monster")
	game._execute_gm_command("add detector")
	assert((game.tool_inventories["thief"] as Array).size() == 3)
	assert(str(game.tool_inventories["thief"][2]["tool_type"]) == "detector")
	game._execute_gm_command("add alarm")
	assert((game.tool_inventories["thief"] as Array).size() == 3)
	assert("已满" in str(game.gm_output))

	game._execute_gm_command("help")
	assert("gold A 50" in str(game.gm_output))
	assert("add robot" in str(game.gm_output))
	assert("trans A" in str(game.gm_output))
	assert("menu" in str(game.gm_output))
	assert("pause" in str(game.gm_output))
	assert("cooldown reset" in str(game.gm_output))
	assert("肾上腺素" not in str(game.gm_output))
	assert("机器人" not in str(game.gm_output))
	for tool_type in game.SHOP_TOOL_TYPES:
		assert(str(tool_type) in str(game.gm_output))
	game._execute_gm_command("menu off")
	assert(not bool(game.main_menu_open))
	game._execute_gm_command("pause")
	assert(bool(game.game_pause_open))
	assert(not bool(game.gm_console_open))
	game._execute_gm_command("pause off")
	assert(not bool(game.game_pause_open))
	game._execute_gm_command("menu on")
	assert(bool(game.main_menu_open))
	assert(not bool(game.gm_console_open))
	game._execute_gm_command("menu off")
	assert(not bool(game.main_menu_open))
	game._execute_gm_command("menu")
	assert(bool(game.main_menu_open))
	game._execute_gm_command("menu off")
	game._execute_gm_command("unknown")
	assert("未知命令" in str(game.gm_output))

	for expected_round in [2, 3]:
		assert(game.current_round == expected_round)
		game._execute_gm_command("next")
		assert(game.phase == "hunt")
		game._execute_gm_command("next")
		assert(game.phase == "shop")
		game._execute_gm_command("next")
		assert(game.current_round == expected_round + 1)
		assert(game.phase == "hide")
	assert(game.current_round == 4)
	game._execute_gm_command("next")
	assert(game.phase == "hunt")
	game._execute_gm_command("next")
	assert(game.phase == "ended")
	game._execute_gm_command("next")
	assert(game.phase == "ended")
	assert("四局比赛已经结束" in str(game.gm_output))

	print("GM console test passed: cooldown reset, English tool IDs, stage flow, gold, give, add, trans, and help.")
	game.free()
	quit(0)
